package hr.fer.zemris.java.hw03.prob1;

/**
 * The Class that represents a token generated by this lexer. It provides
 * getters for accessing its TokenType and value properties.
 * 
 * @author Damjan Vučina
 */
public class Token {

	/** The type of the token. */
	TokenType type;

	/** The value of the token. */
	Object value;

	/**
	 * Instantiates a new token.
	 *
	 * @param type
	 *            the type of the token
	 * @param value
	 *            the value of the token
	 */
	public Token(TokenType type, Object value) {
		if (type == null) {
			throw new IllegalArgumentException("Token type can not be null.");
		}

		this.type = type;
		this.value = value;
	}

	/**
	 * Gets the type of the token
	 *
	 * @return the type of the token
	 */
	public TokenType getType() {
		return type;
	}

	/**
	 * Gets the value of the token.
	 *
	 * @return the value of the token
	 */
	public Object getValue() {
		return value;
	}

}
